### ISSUE TITLE
Server crash structure gen OTG woodland mansion

### ISSUE THREAD

**Issue by Slowwiii** [fonnymunkey/RLCraft-Dregora-Edition#12]
[crash-2024-07-26_11.15.54-server.txt](https://github.com/user-attachments/files/16389742/crash-2024-07-26_11.15.54-server.txt)

**Comment by NLBlackEagle** [comment]
Issue same as: https://github.com/fonnymunkey/RLCraft-Dregora-Edition/issues/13 I just didn't realize this earlier, will be fixed for v1.9
