### ISSUE TITLE
Second world generation fails 

### ISSUE THREAD

**Issue by RudyNahra** [fonnymunkey/RLCraft-Dregora-Edition#15]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [x] Clientside
- [ ] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [x] v1.0.0 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.

I am unable to generate another world after I already made one in the same client session. It fails with "Not enough biome id's available to add all dimensions"
![image](https://github.com/user-attachments/assets/7c981619-8391-45e0-be7d-f06bd430a0c2)

Steps:
1. Generate world in hardcore mode
2. Die
3. Click "Delete World" to go back to main menu
4. Attempt to generate new world with default settings
5. Error

Note that the issue is resolved when I restart the client. Probably because hardcore worlds aren't properly unloaded or deleted when you click "Delete World"

**Comment by NLBlackEagle** [comment]
The issue should be resolved for 1.0.3 👍 Thanks for reporting!
