### ISSUE TITLE
Potion Effects after interacting with village stay at 0 and do not disappear

### ISSUE THREAD

**Issue by OddFlor** [fonnymunkey/RLCraft-Dregora-Edition#16]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [ x] Clientside
- [ ] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [ x] v1.0.0 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.
After trading or interacting with villagers player is affected by potion effects Ex: Explosion 3, Soil 2 ect
After the timer on these potion effects deplete, timer remains at 0 and player is still affected by said potion effect 
When interacting with villagers a second time, potion effects execute their said effect. Ex: (Do not know name of potion effect) Lightning strike, thrown into air ect
Note: Villagers with no name (Name ex: Susberian) do not effect the player with any effect 
To reproduce. Interact with villager twice. Or as many times necessary

**Comment by MariusKurbakovas** [comment]
Can confirm, had this happen too. Effects went away after `Save and quit` and reentering the game (Clientside)

**Comment by fonnymunkey** [comment]
Fixed as of 1.0.1
