### ISSUE TITLE
LoadingScreens incompatible with some AMD GPUs

### ISSUE THREAD

**Issue by JustRandomUser312** [fonnymunkey/RLCraft-Dregora-Edition#17]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [X] Clientside
- [ ] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [X] v1.0.0 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.
When I try to create a new world, Rlcraft Dregora is crashing.

To reproduce you need to use GDlauncher and download there the modpack, then go to the modpack, and then creating new world and there's the crash.

**Comment by fonnymunkey** [comment]
Can you upload/attach the crash report you get when crashing from that?

**Comment by JustRandomUser312** [comment]
[crash-2024-10-19_09.57.20-client.txt](https://github.com/user-attachments/files/17444289/crash-2024-10-19_09.57.20-client.txt)

**Comment by fonnymunkey** [comment]
Try deleting the mod LoadingScreens and retry

**Comment by JustRandomUser312** [comment]
Yes, that's works. Thank you so much!

**Comment by fonnymunkey** [comment]
Fixed as of 1.0.1
