### ISSUE TITLE
Attacks by a flying rider caused java.lang.ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by MariusKurbakovas** [fonnymunkey/RLCraft-Dregora-Edition#18]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [x] Clientside
- [ ] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [x] v1.0.0 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.
Got attacked by Golden Quetzodracl Lvl 2 with a Rider on top of it. Got `java.lang.ArrayIndexOutOfBoundsException` 3 times, my guess would be that this happened each time the rider hit it's own mount with an arrow. Caused no visible issues or crashes.

CraftTweaker log output:
[crafttweaker.log](https://github.com/user-attachments/files/17444695/crafttweaker.log)

**Comment by NLBlackEagle** [comment]
Thanks for reporting this!

**Comment by NLBlackEagle** [comment]
Solved for 1.0.2 (Make sure to update to 1.0.3 though!)
