### ISSUE TITLE
Game crash when pressing F3 while zooming in

### ISSUE THREAD

**Issue by ImposterCrafty** [fonnymunkey/RLCraft-Dregora-Edition#20]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [x ] Clientside
- [ ] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [ x] v1.0.0 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.
Pressing F3 while using optifine zoom 'C' crashes the game
![image_2024-10-19_170259412](https://github.com/user-attachments/assets/8f5f1f39-fd42-43a7-b937-07b01d291573)

**Comment by fonnymunkey** [comment]
F3 + C is the Vanilla Minecraft keybind to force a crash for debugging purposes, as it says in the crash report.

**Comment by ImposterCrafty** [comment]
> F3 + C is the Vanilla Minecraft keybind to force a crash for debugging purposes, as it says in the crash report.

Is there a way to disable this? Most sources say it crashes after 10 seconds of holding it but it crashes instantly for me.
