### ISSUE TITLE
The throwing stone axe shows a bug.

### ISSUE THREAD

**Issue by 3081925122** [fonnymunkey/RLCraft-Dregora-Edition#21]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [√ ] Clientside
- [ ] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [√ ] v1.0.0 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.
I'm not good at English. The following is translated for me by AI。
Throw an attack on the monster with a throwing stone axe. It bounces back onto me. There is an error reported in the lower left corner. ERRDR: java.lang.NullPointerException,I should send out the log, but I don't know how to send it to you.

**Comment by ImposterCrafty** [comment]
i also get this error when attacking other players in a lan world, first it showed one error, later showed 3 every hit
![Uploading image_2024-10-19_185338645.png…]()

**Comment by fonnymunkey** [comment]
This should be fixed as of 1.0.1
