### ISSUE TITLE
Annoying amphi behaviour 

### ISSUE THREAD

**Issue by Iquryy** [fonnymunkey/RLCraft-Dregora-Edition#23]
#### Is your feature request related to a problem? Please describe.
▶️A clear and concise description of what the problem is. Ex. I'm always frustrated when...◀️
1. The Amphi dropping you when you take damage (whether you're on fire, withered, or poisoned) occurs if the Amphi is locked onto a mob that attacked you.
2. Amphi targeting a mob that attacked you.
#### Describe the solution you'd like.
▶️A clear and concise description of what you want to happen.◀️
1. Not being dropped when you mount the amphi while being damaged.
2. Amphi not going full-on kill mode on the mob.

#### Describe alternatives you've considered.
▶️A clear and concise description of any alternative solutions or features you've considered.◀️

#### Description aka Additional context.
▶️Add any other context or screenshots about the feature request here.◀️

https://github.com/user-attachments/assets/d8de0974-0552-48fc-a5ad-5181677c6403

Just imagine the clip I sent with you being in middle of combat getting damaged, and dropped from the amphi while the amphi just going ham on the mob.

▶️And Delete the lines in between the ▶️◀️ icons◀️

**Comment by NLBlackEagle** [comment]
This was caused by the in_wall damage trigger that would dismount you from your mount, I think it has been fixed for 1.0.1 after we realized in_wall was probably a tad too much of a flying nerf
