### ISSUE TITLE
crasheo

### ISSUE THREAD

**Issue by ElLempo** [fonnymunkey/RLCraft-Dregora-Edition#24]
Hello,

I hope you are doing well. I wanted to inform you about an issue I am experiencing with the Dregora mod in RLCraft. While trying to play, I am encountering an error with the code -1073741819, which causes the game to crash unexpectedly.

I’ve tried several solutions, such as increasing the RAM allocation, ensuring I have the correct version of Java (Java 8), and checking mod compatibility. However, the issue persists, preventing me from fully enjoying the game.

If you need more information, such as error logs or details about my setup, I would be happy to provide it. I appreciate your work on this mod and any assistance you can offer to resolve this issue.

Thank you in advance for your attention.

**Comment by fonnymunkey** [comment]
Can you upload/attach the crash report from the crash report folder in your installation location? Otherwise if the crash report doesn't exist, upload the latest.log file from the logs folder.
(Error codes aren't useful when it comes to modded minecraft)

**Comment by NLBlackEagle** [comment]
Assuming the issue has been resolved due to lack of response? Feel free to re-open this at any time if this is not the case and you get the crash again, do make sure to include a crash report/latest.log like fonnymunkey suggested
