### ISSUE TITLE
No Random Spawns

### ISSUE THREAD

**Issue by GFnekowo** [fonnymunkey/RLCraft-Dregora-Edition#25]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [ x] Clientside
- [ ] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [ x] v1.0.0 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.
Everyone is spawning at the same spawn point, instead of spawning in random spots. I thought maybe they changed it but the config is still set to 20000 spawn radius so im not sure why we keep spawning there

**Comment by NLBlackEagle** [comment]
With the latest release (1.0.3) spawning has been improved where it properly follows the globalgamerule spawnradius. When you update make sure to backup your world, install it as new (do not overwrite, make a new instance) and once finished drop in your world again.
