### ISSUE TITLE
Unable to right-click logs or planks with axe

### ISSUE THREAD

**Issue by polykatt** [fonnymunkey/RLCraft-Dregora-Edition#26]
#### RLCraft Dregora Server/Client
- [x] Clientside

#### Dregora Version
- [x] v1.0.0 RLCraft Dregora

#### Description
Cant use axe to get planks or sticks from placed logs or planks that were obtained from chests
Edit: Actually it seems like this is just happening randomly with any wood not just those obtained from chests :/

**Comment by ImposterCrafty** [comment]
From what I experienced there needs to be a 'hard' block under the wood like stone to be able to chop the wood

**Comment by polykatt** [comment]
oh that's true thx!
