### ISSUE TITLE
Potion Sickness Bug???

### ISSUE THREAD

**Issue by Iquryy** [fonnymunkey/RLCraft-Dregora-Edition#27]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [ ] Clientside
- [x] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [x] v1.0.0 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.
Full set of silver with ank shield in off-hand gives potion sickness

https://github.com/user-attachments/assets/9af21422-fd55-450e-96fe-bdf41f87ac60

I mean it's true I was moving armor, but it also happens when I've not touched both and randomly I get the potion sickness
![image](https://github.com/user-attachments/assets/e50c8487-6d08-42df-81b2-b3628ead2acd)

**Comment by Iquryy** [comment]
This actually could be due to the shield getting damaged and healed with mending in combat

**Comment by NLBlackEagle** [comment]
Thanks for reporting, this was a issue we noticed right before deciding getting rid of silver sickness altogether so I guess I can safely close this issue now 👍 

Thanks for reporting this!
