### ISSUE TITLE
Trolls doing T pose

### ISSUE THREAD

**Issue by drewbee82** [fonnymunkey/RLCraft-Dregora-Edition#34]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [x ] Clientside
- [ ] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [ ] v1.0.0 RLCraft Dregora
  [x] v.1.0.1 RLcraft Dregora
#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.
While being attacked by two trolls, they start to chase and just go into a T Pose and freeze.  The first hit registers, but after that they're just frozen there like a statue and no damage.

**Comment by fonnymunkey** [comment]
Trolls will freeze and turn into statues if you lead them into sunlight.
