### ISSUE TITLE
Sivler armor

### ISSUE THREAD

**Issue by Luong-Trieu-Vy** [fonnymunkey/RLCraft-Dregora-Edition#35]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [ x] Clientside
- [ ] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [ x] v1.0.1 RLCraft Dregora

#### Description
▶️hello i thank you for my favorite mod being able to update to the new version but along with that during the experience there are some problems that make me confused. That lies in my silver armor. Why do i own the full armor + akh shield but i still have to receive adverse effects from other mods? someone please explain to me

**Comment by fonnymunkey** [comment]
Silver armor and Ankh Shield are designed to typically remove "magical" effects, some effects are not magical such as bleeding and as such are not removed by either.
