### ISSUE TITLE
Incorrect Commands given for the Pregen Mod

### ISSUE THREAD

**Issue by Rameez3** [fonnymunkey/RLCraft-Dregora-Edition#36]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [] Clientside
- [X] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [ ] v1.0.0 RLCraft Dregora
- [X] v1.0.1 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.

- The commands given for pregening the world is wrong: 

Given Commands:
/pregen utils setPriority pregenerator
/pregen timepertick 250
/pregen gen startradius square 0 0 b20000

Commands should be:
/pregen utils priorty PREGENERATOR
/pregen utils timePerTick 250
/pregen start gen radius word SQUARE 0 0 20000b

priority is spelled wrong as "priorty" in the console commands.

**Comment by fonnymunkey** [comment]
Those are the commands for the latest version of pregenerator that does not work with the pack.
The server readme file specifically links and tells you to use version 2.5.1, in which the included commands are correct.
