### ISSUE TITLE
World loading issue

### ISSUE THREAD

**Issue by spencerCrowell** [fonnymunkey/RLCraft-Dregora-Edition#37]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [x] Clientside
- [ ] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [x] v1.0.0 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.
i loaded a new world, and a menu popped up explaining an issue loading the world, and provided this link:
https://mclo.gs/Geui5kU
my character continually took damage as if i was suffocating under gravel, but there were no blocks, and the screen was black

**Comment by NLBlackEagle** [comment]
Does the issue still happen on 1.0.3?

**Comment by spencerCrowell** [comment]
The issue has not happened apart from the one report I made, and I have not seen it on 1.0.3 either.

**Comment by NLBlackEagle** [comment]
Ill mark the issue as resolved then, if it pops up feel free to re-open it 👍
