### ISSUE TITLE
I keep getting error code 1

### ISSUE THREAD

**Issue by guzzlinggranny** [fonnymunkey/RLCraft-Dregora-Edition#39]
When I try starting it gives me error 1, this happens for regular rlcraft aswell. Ive followed all steps and guides but it just doesnt want to work. All other mods on curseforge work fine.

**Comment by fonnymunkey** [comment]
Either upload the crash report or the latest.log file from the logs folder, error codes are meaningless for modded minecraft.

**Comment by guzzlinggranny** [comment]
I solved it by nuking all files in the appdata folder
