### ISSUE TITLE
problems with server

### ISSUE THREAD

**Issue by Aaron112207** [fonnymunkey/RLCraft-Dregora-Edition#40]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [ ] Clientside
- [ x] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [x ] v1.0.1 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.
when joining server quest don't show, and cant make flint shards i am right clicking on stone but nothing happens. when i play single player everything works fine.
if this is stupid question i am sorry, i just have no idea what i am doing wrong.

**Comment by NLBlackEagle** [comment]
This might be a tps issue, could you send the output of /spark profiler start --timeout 30 --thread *

**Comment by Aaron112207** [comment]
I don't think so because everything else works fine and TPS was good. I am busy right now I will send it leater

**Comment by NLBlackEagle** [comment]
Assuming the issue has been solved, be it through a re-install or update to 1.0.2 or 1.0.3  feel free to re-open if it was not
