### ISSUE TITLE
world generation issues

### ISSUE THREAD

**Issue by 1026761665** [fonnymunkey/RLCraft-Dregora-Edition#44]
If I used the command /pregen gen startradius square 0 0 b9000 to pregenerate chunks in version 1.0.1, can I copy the save to version 1.0.2 and use the command /pregen gen startradius square 0 0 b9000 0 Retrogen to regenerate new structures?

**Comment by 1026761665** [comment]
I used the SERVER README OR DIE.txt to generate "YOU SHOULD PREGEN YOUR WORLD IF YOU PLAN TO RUN A SERVER WITH MORE THAN 4 PLAYERS:

How to Pre-generate a 20k block radius (Square) world:

Download: https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator/files/3490718
Place that jar in your mods folder (Server mods folder if a server) and verify the chunkpregenerator version is 2.5.1

Run these commands (In console if a server, in game if singleplayer):

/pregen utils setPriority pregenerator
/pregen timepertick 250
/pregen gen startradius square 0 0 b20000".

**Comment by NLBlackEagle** [comment]
There are no new structures in 1.0.2, only major versions such as 1.1.0 or 2.0.0 would contain world-altering changes.
To continue on your world for which we recommend 1.0.3 you'd have to backup your world, install a new server & new clients, then add your world backup to that instance.
