### ISSUE TITLE
Loading World

### ISSUE THREAD

**Issue by pikoage** [fonnymunkey/RLCraft-Dregora-Edition#45]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [x] Clientside
- [x] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [ ] v1.0.0 RLCraft Dregora
- [X ] v.1.0.2 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.
When i updated my rlcraft from version 1.0.0 to 1.0.2 i can't join to my own world as a single player. I have everytime Loading world without crashes.

**Comment by NLBlackEagle** [comment]
Create a new instance (Now with 1.0.3) and drag your world over to the new instance, updating the same instance will likely result in errors like these, If this doesn't fix the issue chances are that your world somehow got corrupted and you'd need to remake a world.

Feel free to re-open this issue with a latest.log if my directions do not solve the issue.
