### ISSUE TITLE
Ingredients and recipe for potion of lightning resistance

### ISSUE THREAD

**Issue by HanosThePlacid** [fonnymunkey/RLCraft-Dregora-Edition#50]
#### Is your feature request related to a problem? Please describe.
▶️
Lightning Dragons are strong but luckily we have lightning resistance potions oh wait. You cant brew it. I even checked the game files for the recipe. 
◀️

#### Describe the solution you'd like.
▶️
• for fire dragons we have: **blaze powder+Slimeball -> magma cream -> fire resistance**
• for ice dragons we have: **frost powder+Slimeball -> glacier cream -> Ice resistance**
• so for lighting dragons we should have: **lighting related item+Slimeball>electric or voltaic cream -> lightning resistance**

My suggestions would be: Lightning Lily or Lightning Lily Mixture
◀️

#### Describe alternatives you've considered.
▶️
Alternatively Lightning Blast Charge from Lycanitesmobs could be used to craft the voltaic cream for lighting resistance potion 
◀️

#### Description aka Additional context.
▶️
![image](https://github.com/user-attachments/assets/8c08c60b-dbbf-4973-92dd-d2621f6c6ca5)
![image](https://github.com/user-attachments/assets/c7becf46-14cc-43a2-9332-67ba83b8fe9b)
![image](https://github.com/user-attachments/assets/8a6dace8-2187-4148-aae1-208169480bc8)
◀️

**Comment by NLBlackEagle** [comment]
Oh yeah good find and thanks for the suggestion, I agree with  Lightning Lily functioning as base for the potion! :)
Will be added for 1.0.4!

**Comment by HanosThePlacid** [comment]
> Oh yeah good find and thanks for the suggestion, I agree with Lightning Lily functioning as base for the potion! :) Just completed it and will be in 1.0.4!

Well that was fast. :D Thx a lot

**Comment by NLBlackEagle** [comment]
Seems it was a bit too fast actually, had a chat with Kotlin & Shivaxi and the reason it was uncraftable instead of hard or very hard to obtain is because Shiv intended lightning dragons to remain a enemy to be reckoned with.

I'll be reverting the commit in which I gave it a crafting recipe but hey now you got a solid reason :)
