### ISSUE TITLE
Optifine installer gui removal

### ISSUE THREAD

**Issue by balintcristian** [fonnymunkey/RLCraft-Dregora-Edition#58]
I tried running the dregora server on linux ( i had it installed on windows and moved it to google drive) and i get an empty window relating Optifine even if running java with --nogui with a bash or from cli.
Server start is stuck there because of that white window that renders nothing in it, any idea/tips?
the last server console info is: loading cofing config/mod-director/optifine.url.json and it's stuck there, no crash, nothing.
I think there's supposed to be some checkboxes or something for me to interact inside that window, but nothing renders in it.
![Screenshot from 2024-11-14 23-04-46](https://github.com/user-attachments/assets/2992974a-cad3-447f-8496-394077e5a225)

**Comment by fonnymunkey** [comment]
Delete !mod-director from the mods folder

**Comment by balintcristian** [comment]
Actually deleted the mod directory and the served worked, but i think the mod will generate the config again. So better safe then sorry, i'm guessing it was a client side mod for wrapping things together? Anyways thanks for the help, it works. 

The issue is closed

**Comment by balintcristian** [comment]
The issue is closed
