### ISSUE TITLE
error when join server

### ISSUE THREAD

**Issue by pepea23** [fonnymunkey/RLCraft-Dregora-Edition#59]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [ ] Clientside
- [X ] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [ X] v1.0.0 RLCraft Dregora

#### Description
when lunch server and join encounter server crashing by this error log any crue to fix it ?

[rl log.txt](https://github.com/user-attachments/files/17784535/rl.log.txt)

[message.txt](https://github.com/user-attachments/files/17784540/message.txt)

**Comment by fonnymunkey** [comment]
You need to reinstall and update to 1.0.3, older versions are not supported.
