### ISSUE TITLE
FTB Launcher Improper Texture Handling

### ISSUE THREAD

**Issue by emckini1** [fonnymunkey/RLCraft-Dregora-Edition#60]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [x] Clientside
- [ ] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [x] v1.0.3 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.
I downloaded RLCraft Fregora from curseforge via the FTB Launcher. The game works fine so far, but is missing texture for various items. Examples include multiple drops (Spectral Bolt Charge and Aqual Pulse Charge) from Lycanite Mobs. I am missing Heart Crystal Shard from Scaling Health, Recall Potion from Bountiful Baubles, and Ravaging Essence from Defiled Lands. I have tried deleting and reinstalling. I have tried repairing. Neither fixes the issue.

**Comment by fonnymunkey** [comment]
The FTB launcher is broken and does not properly handle Resourcepacks, use the Curseforge launcher or the Prism launcher
