### ISSUE TITLE
Rubberbanding/freezing every minute

### ISSUE THREAD

**Issue by 0Lynk** [fonnymunkey/RLCraft-Dregora-Edition#61]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [ ] Clientside
- [x] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [x] v1.0.3 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.

Rubberbanding/freezing occurs nearly every minute, persisting for approximately 1 to 2 seconds.
The log reports are similar to: [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 8731ms behind, skipping 174 tick(s)
The I/O and hardware issues have been excluded. 

has been pre-generated.
Reboot or reinstall the server did not resolve the problem.

Spark profile:
https://spark.lucko.me/v7Sb6OSJhl
Full logs:
https://mclo.gs/k8aLUX4

![4be8ef7c4df76f2a9f48b9259686bff8](https://github.com/user-attachments/assets/5b7303d9-3dc6-40dc-a418-e6cf41443e63)

**Comment by Emtecsus** [comment]
update the fermiumASM mod, it's a problem of the 5.23 version

**Comment by fonnymunkey** [comment]
Both FermiumASM and RLTweaker need to be updated, the updated files that are backwards compatible with 1.0.3 have been posted in the Discord's rl-tech-support channel in the meantime while waiting for 1.0.4/1.1.0

**Comment by 0Lynk** [comment]
Updated FermiumASM and RLTweaker,has resolved.
