### ISSUE TITLE
The RLDregora Test Server has been crashing 

### ISSUE THREAD

**Issue by bumanjihui** [fonnymunkey/RLCraft-Dregora-Edition#63]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [ ] Clientside
- [x] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [x] v1.0.3 RLCraft Dregora
#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.
The RLDregora Test Server crashed a week ago, but none of you noticed the problem, and you haven't rebooted the server once, so I recommend you reboot it once a day

**Comment by fonnymunkey** [comment]
The RLDregora Test Server is specifically for development testing different mods and changes and is liable to be reset at any point, you should not be playing on it, there are many other actual servers meant for playing either in the Bisect Multiplayer list or listed on the RLCraft Discord server.
