### ISSUE TITLE
No natural spawning

### ISSUE THREAD

**Issue by Spyro1502** [fonnymunkey/RLCraft-Dregora-Edition#68]
#### RLCraft Dregora Server/Client
- [ ] Clientside
- [x] Serverside

#### Dregora Version

- [x] v1.0.3 RLCraft Dregora

#### Description
After a while playing, we noticed no more mobs were spawning in the overworld, at least no "natural" spawning

Mounted RLCraft mobs do spawn (like mounted gryphons or dragons
Dragon, fairies do spawn
Bosses from lycanites dungeons spawns too

Everything else doesn't work, no mobs at nightime (or very, very few)
Spawners spawns absolutely nothing

It seems to only happens in the overworld, nether, end and Lost cities still seems to spawn monsters as expected, maybe just slightly less ?

I recently went to the bug meteor crater and nothing is there, not a single mob beside an ice dragon

Spawner here not spawning even when staying around
![2024-12-03_14 42 43](https://github.com/user-attachments/assets/f371865c-3447-47b3-af30-071662b272df)

Here are the existing mobs around when given a glowing effect to see them, 1 chupacabre, then only armor stands and mimics
![2024-12-03_14 44 56](https://github.com/user-attachments/assets/7d75532c-7dff-4c8f-a7fd-7ca7d65a4c33)

**Comment by Spyro1502** [comment]
PS : I stayed AFK next to the spawner while writing this bug report, server is in hard, and I am in survival, so I confirm the spawning doesn't work

**Comment by KameiB** [comment]
The Roguelike Dungeons spawners are custom.
Do mobs not spawn even from Lycanites dungeons spawners?

**Comment by Spyro1502** [comment]
No spawner actually works in the overworld, Lycanites dungeons ones either, only the bosses are here

We had a Lycanites event, mobs do spawn during that one

Spawners in lost cities and nether seems to work

**Comment by fonnymunkey** [comment]
This sounds like the gamerule doMobSpawning was disabled, which would result in only the custom spawning handlers running and not natural spawning/spawners.

Try reinstalling the server and copying over the world, and if there is still an issue, try creating a new world and see if the issue persists.

**Comment by Spyro1502** [comment]
It seems a bit weird, as I checked the gamerule do say doMobSpawning is "true", and that only happens in the overworld. So I guess there's something causing this problem in that specific dimension as other ones works perfectly.

Also had the occasion to test, the **blood moon** does not work.

I will still try and see if anything is fixed

**Comment by Spyro1502** [comment]
Okay so after a server reset I simply set the map back on it and it's working well again, I don't know what caused this but that's fixed, thank you !
